//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTracker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMovieDetail
    {
        public int Id { get; set; }
        public int UserMovieMappingId { get; set; }
        public int StatusId { get; set; }
        public Nullable<decimal> UserRating { get; set; }
        public string Comments { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual UserMovieMapping UserMovieMapping { get; set; }
    }
}
