//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTracker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMovieMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMovieMapping()
        {
            this.UserMovieDetails = new HashSet<UserMovieDetail>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int MovieId { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMovieDetail> UserMovieDetails { get; set; }
    }
}
